name: Scrape

on:
  schedule:
    - cron: "0 16 * * *" # 4 p .m. every day UTC, which is 10 a.m. CST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - run: pipenv install jupyter requests bs4 --python `which python`
    - name: Run scraper
      run: pipenv run jupyter execute scrape.ipynb
    - name: Add and commit	
      run: |-	
        git add .	
        git config user.name "elleperry"	
        git config user.email "elleperry84gmail.com"	
        git commit -m "Latest data" 	
    - name: Push	
      run: git push
